import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { RamadanDay } from '../services/ramadanService';
import { formatPrayerTime } from '../services/ramadanService';

/**
 * Format date for display in PDF
 */
const formatDate = (dateString: string): string => {
  const date = new Date(dateString.split('-').reverse().join('-'));
  return date.toLocaleDateString('en-US', { 
    weekday: 'short', 
    day: 'numeric', 
    month: 'short'
  });
};

/**
 * Generate a PDF of the Ramadan calendar
 */
export const generateRamadanCalendarPDF = (
  calendar: RamadanDay[],
  location: string,
  year: number
): void => {
  // Create a new PDF document
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  // Add title and metadata
  doc.setFontSize(20);
  doc.setTextColor(0, 100, 0); // Dark green color
  doc.text(`Ramadan Calendar ${year}`, 14, 22);
  
  // Add location and date
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Location: ${location}`, 14, 30);
  
  // Add current date
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`Generated on: ${currentDate}`, 14, 36);

  // Add logo or decoration
  doc.setFontSize(16);
  doc.setTextColor(0, 100, 0);
  doc.text('☪️ Ramadan Kareem', doc.internal.pageSize.width - 60, 22);

  // Prepare table data
  const tableData = calendar.map(day => [
    day.date.hijri.day,
    formatDate(day.date.gregorian.date),
    formatPrayerTime(day.timings.Imsak),
    formatPrayerTime(day.timings.Fajr),
    formatPrayerTime(day.timings.Dhuhr),
    formatPrayerTime(day.timings.Asr),
    formatPrayerTime(day.timings.Maghrib)
  ]);

  // Create table
  autoTable(doc, {
    startY: 45,
    head: [['Day', 'Date', 'Suhoor', 'Fajr', 'Dhuhr', 'Asr', 'Iftar']],
    body: tableData,
    theme: 'grid',
    styles: {
      fontSize: 10,
      cellPadding: 3,
      lineColor: [0, 100, 0],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: [0, 100, 0],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [240, 248, 240],
    },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 40 },
      2: { cellWidth: 25, fontStyle: 'bold' },
      3: { cellWidth: 25 },
      4: { cellWidth: 25 },
      5: { cellWidth: 25 },
      6: { cellWidth: 25, fontStyle: 'bold' },
    },
  });

  // Add footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(
      'Generated by Ramadan Planner App',
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 20,
      doc.internal.pageSize.height - 10
    );
  }

  // Save the PDF
  doc.save(`Ramadan_Calendar_${year}.pdf`);
};